### ISSUE TITLE
Seg. fault when testing on simulated data

### ISSUE THREAD

**Issue by SpheMakh** [sievers/corrcal2#1]
at this line of the test_corrcal2_fof.py file:

```
asdf=fmin_cg(corrcal2.get_chisq,gvec*fac,corrcal2.get_gradient,(big_vis+500*src,mycov,ant1,ant2,fac))
```

This is the output from the debuger. 

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff2df8429 in apply_gains_to_mat () from libcorrcal2_funs.so
```

**Comment by sievers** [comment]
There's something inconsistent about matrix sizes for that to happen.  Do
you have a test script I can look at that reproduces the problem?

**Comment by SpheMakh** [comment]
The script is at *hippo:/home/makhathini/jon/test_corrcal_fof.py*

and the visibility, antenna, and uv data are at  *hippo:/home/makhathini/jon/data*

**Comment by sphemakh** [comment]
- Correct paths:

The script is at _hippo:/home/sphe/jon/test_corrcal_fof.py_

and the visibility, antenna, and uv data are at  _hippo:/home/sphe/jon/data_

**Comment by sievers** [comment]
OK, think I fixed it.  Issue is that code expects antennas to be int64, and
you were reading them in as int32.  I just added these after the read and
it all worked:

ant1_org=numpy.asarray(ant1_org,dtype='int64')
ant2_org=numpy.asarray(ant2_org,dtype='int64')

Jon

**Comment by sphemakh** [comment]
Cool, that worked.
